from transformers import AutoTokenizer, AutoModelForTokenClassification, T5ForConditionalGeneration, T5Tokenizer
import torch

# Load the model and tokenizer
tokenizer = AutoTokenizer.from_pretrained('ml6team/keyphrase-generation-t5-small-inspec')
model = AutoModelForTokenClassification.from_pretrained('ml6team/keyphrase-generation-t5-small-inspec')

def extract_keywords(texts):
    for text in texts:
        keywords = []
        # Tokenize the text
        inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)
        # Get the model's output
        outputs = model(**inputs)
        # Get the predictions
        predictions = torch.argmax(outputs.logits, dim=-1)
        # Extract the keywords
        for i, token in enumerate(inputs["input_ids"][0]):
            if predictions[0, i].item() == 1:
                keywords.append(tokenizer.decode([token]))
        print(', '.join(keywords))

# Test the function
texts=["Visiting New York City? Experience 5 must-see attractions, handpicked and packaged together at a 40% savings, with New York CityPASS® tickets. Spend less time planning and more time exploring. Visit the attractions at your own pace, in any order. Valid for 9 consecutive days including the first day of use. Buy online for instant mobile delivery. Get admission to 5 attractions.Includes: •Empire State Building Observatory- AM/PM Experience, including 86th Floor Observatory admission and entry to the 2nd Floor Museum, plus bonus same-night general admission •American Museum of Natural History- Admission to permanent Museum halls, including over 40 galleries, plus a choice of one ticketed exhibition, the Davis Family Butterfly Vivarium, giant-screen film, or the Hayden Planetarium Space Show (based on availability; Invisible Worlds not included) Plus choose 3 of the following: •Top of The Rock® Observation Deck- General Admission •Ferry Access to Statue of Liberty and Ellis Island- General Admission ticket for one Statue City Cruises ferry ride to and from Liberty Island and Ellis Island, audio guides, and admission to the Statue of Liberty Museum and Ellis Island National Museum of Immigration (Crown Tickets and Pedestal Access not included)•9/11 Memorial & Museum- General Admission •Circle Line Sightseeing Cruises- One regularly scheduled Landmarks Cruise, Liberty Midtown Cruise or Liberty Super Express Cruise (check circleline.com for current schedules)•Intrepid Museum- General admission, including the Space Shuttle Pavilion, the submarine Growler, the immersive Kamikaze experience, and all temporary exhibitions •Guggenheim Museum- General admission to the Guggenheim’s collection and special exhibits, plus a free digital guide (accessed via personal mobile device)Plan Your Trip:Visit my.citypass.com to make reservations (if required), access tickets and view attraction details."]
extract_keywords(texts)


"""
texts = ["Manhattan brings to mind grand skyscrapers, taxi cabs, and a world-class attitude all of its own. See all this and more as an expert pilot flies you over NYC on a 15 or 20-minute helicopter tour. Soar over the Statue of Liberty, Central Park, Brooklyn Bridge, Madison Square Garden, among other landmarks. After take-off from the Downtown Heliport, swing down over lower Manhattan to see the skyline and streets below. Swoop over Battery Park to glance at Wall Street and its labyrinth of streets. Then sail over to Governor's Island, an island once reserved only for the city's dignitaries that now hosts summer concerts and public art. Then, fly over Ellis Island and see Lady Liberty shining brightly in the distance. Cruise right up to her eye for a new perspective of the Statue of Liberty. Enjoy all this before heading up the Hudson past the piers of Chelsea and the lights of Broadway. On your way back to the pier, head around the Empire State Building, Brooklyn Bridge, and fly over Ground Zero where you can have a look at the exceptional work they're doing at the sight. Continue past Madison Square Garden and the Intrepid Air and Space Museum. See Central Park as your flight turns around to return to the heliport. Sights included in the 15-Minute tour: Statue of LibertyEllis IslandOne World Trade Center9/11 MemorialBrooklyn BridgeBattery ParkWall Street/Financial DistrictEmpire State BuildingChrysler BuildingMadison Square GardenTimes SquareU.S.S. Intrepid Sea, Air, and Space MuseumCentral Park Sights included in the 20-Minute tour: Brooklyn BridgeBattery ParkWall StreetStatue of LibertyEllis IslandOne World Trade Center9/11 Memorial SiteEmpire State BuildingChrysler BuildingMadison Square GardenU.S.S. Intrepid MuseumTimes SquareCentral ParkGrant’s TombGeorge Washington BridgeHarlem and Harlem RiverThe Bronx and Yankee StadiumPalisades CliffsSpuyten Duyvil Bridge",
         "Experience New York at sunset on a cruise of the harbor, and take in all the sights and lights of Manhattan aboard a climate-controlled boat. Grab your friends, family, and coworkers - or even a random stranger - and embark on an unforgettable journey of the harbor with 'Lady Liberty' keeping watch. With a drink in your hand, purchased from the fully stocked bar, feel the breeze on your face and be mesmerized by the shimmering skyline. Get endless photo opportunities to make you an Instagram star as you sail past legendary attractions such as the Statue of Liberty and get perfect views of the Freedom Tower - One World Trade Center, Empire State Building, Pier 54 (Titanic Pier), Battery Park, and more. See where millions of immigrants were processed when they arrived in America at Ellis Island, cruise past Governors Island, the South Street Seaport, and Brooklyn Bridge. Marvel at unrivaled views of the Manhattan Bridge, Williamsburg Bridge, and Chrysler Building, and discover the East Village, United Nations Building, and USS Intrepid Pier from a different perspective.",
         "See all that NYC has to offer with the official all inclusive NEW YORK PASS. Visit 100+ attractions with a single mobile pass for one great price. Check in the view from the top of Empire State Building, take a ferry ride to the Statue of Liberty, hop on and off a Big Bus Tour, and more. Simply choose how many days you'll be in New York and get unlimited admission to many of the city's best attractions, tours, and experiences. Activate your pass at the first attraction or tour you go to. Once activated, your pass records when and where you first used it and how long it will remain valid for. Your New York Pass is then valid for the number of consecutive days that you've purchased. Activities include: Popular Experiences • Empire State Building • Big Bus 1-Day Downtown & Uptown Hop-on Hop-off Tour • Top of the Rock Observation Deck • 9/11 Memorial & Museum • Edge • One World Observatory • Statue of Liberty Ferry & Ellis Island Immigration Museum • Best of NYC Cruise by Circle Line • Madame Tussauds New York • Central Park Bike Rental by Unlimited Biking • Guggenheim Museum • The RIDE Museums & Galleries • American Museum of Natural History • MoMA - Museum of Modern Art • Intrepid Museum • Museum of Sex • Whitney Museum of American Art • Fotografiska New York • Museum of the City of New York • New York Historical Society • Museum of Arts and Design • Museum of Jewish Heritage • Skyscraper Museum • New York Hall of Science • Museum at Eldridge Street • International Center of Photography • MOMA PS 1 • Staten Island Museum • The Paley Center for Media • The Museum of Chinese in America • Cooper Hewitt Smithsonian Design Museum Family-friendly • Central Park Bike Tour by Unlimited Biking • 9/11 Museum Workshop: Hands-On 9/11 Tour • Marvel & DC Superheroes Walking Tour • Yankee Stadium Tour • LEGOLAND® Discovery Center, New Jersey or Westchester • Staten Island Zoo • Staten Island Children’s Museum Hidden Gems • New York Botanical Garden • Catacombs by Candlelight Tour • Harlem Jazz Series – Tuesday and Friday • New Museum • Cathedral of St. John the Divine • Snug Harbor Cultural Center & Botanical Garden • ARTECHOUSE New York Tours & Cruises • Central Park TV & Movie Sites Walking Tour • Rockefeller Center Tour • The Official Chinatown Walking Tour • How Money Was Made: Wall Street Walking Tour • Harbor Lights Cruise by Circle Line • Clipper City Tall Ship – Statue of Liberty Cruise (seasonal) • The Official Little Italy Walking Tour • New York City News Media Tour • Brooklyn Bridge & DUMBO Neighborhood Walking Tour • Brooklyn Bridge Guided Bike Tour by Unlimited Biking • See 30+ Top New York Sights Walking Tour Attractions and tours are subject to change. Check the digital guide for an up-to-date attraction line-up including opening times and instructions on how to access each attraction before you go. Some tours and attractions require advance reservations. * Savings based on sample itineraries on Go City website.",
         "Visitors to the Intrepid Museum can experience a legendary aircraft carrier, the first space shuttle, the world’s fastest jets, and a Cold War-era submarine. Discover a museum that employs history and technology to inspire and advance innovation by developing the next generation of leaders in science, technology, engineering, and math. The Intrepid Museum is dedicated to the exhibition and interpretation of history, science, and service from its home on board the aircraft carrier Intrepid, a National Historic Landmark. The former aircraft carrier USS Intrepid was launched in 1943 and fought in World War II, surviving five kamikaze attacks and one torpedo strike. The ship later served in the Cold War and the Vietnam War. It was decommissioned in 1974, and today is berthed on the Hudson River. You get the chance to visit 4 decks of this great ship: • Hangar Deck: A great place to start your visit and our main indoor exhibit space, the hangar deck takes you through both the hardware and humanity of Intrepid • Flight Deck: Get an up-close look at more than two dozen authentically restored aircraft, look inside the Restoration Tent, and take a walk through history on Intrepid's island and bridges. - Gallery Deck: Located between the flight deck and hangar deck, the gallery deck features the combat information center (CIC), squadron ready room, and marine berthing • Third Deck: Learn about shipboard life in Intrepid's restored galley, enlisted mess, and crew berthing The Space Shuttle Pavilion showcases Enterprise, the prototype NASA orbiter that paved the way for the space shuttle program. Dynamic exhibit zones feature original artifacts, photographs, audio, and films that immerse visitors in the science and history of Enterprise and the space shuttle era. Special Exhibit: Apollo: When We Went to the Moon, on view from March 25th to September 2nd. Step back in time to one of humanity's greatest adventures at the Intrepid Museum's latest exhibit, 'Apollo: When We Went to the Moon.' Immerse yourself in the captivating story of the Apollo missions, where you'll discover the triumphs and challenges faced by the brave astronauts who journeyed to the lunar surface. Experience the thrill of space exploration as you walk through a recreation of the Apollo 11 command module, the spacecraft that carried Neil Armstrong, Buzz Aldrin, and Michael Collins to the moon and back. Marvel at artifacts from the Apollo program, including moon rocks and lunar landing gear, and learn about the cutting-edge technology that made these historic missions possible. But the exhibit isn't just about the past—it's also about the future. Explore how the Apollo missions paved the way for future space exploration, including NASA's ambitious plans to return astronauts to the moon and eventually journey to Mars.",
         "NYC: New Year's Eve Harbor Cruise with Gourmet Lunch",
         "Discover the monuments of Washington DC on a day trip from New York City. Learn about the government and dive into key historic moments like the American Revolution and Civil War. See sights like Lincoln Memorial, Vietnam Veterans Memorial, and Arlington Cemetery. Depart New York City and travel in a spacious and air-conditioned bus to Washington DC. Relax on the scenic drive and head to Capital Hill once you get to DC to find out where congress meets. Stop outside the White House for a photo opportunity and hear more from your guide about the inner workings of the building. Admire the memorials to Jefferson, who wrote the Declaration of Independence, and Lincoln who ended slavery in 1860. Visit the Iwo Jima and Vietnam Veterans Memorials to understand how these events changed the country. Visit Arlington Cemetery where over 200,000 soldiers since the Civil War and the Kennedys were buried. Finally, spend some time at the magnificent Union Station.",
         "Experience the magic of the season on a luxurious Christmas Day gourmet brunch or dinner cruise aboard New York’s glass-enclosed Bateaux, Manhattan’s most premium experience on the water. You and your guests will enjoy a holiday 3-course, plated brunch or dinner freshly prepared by a chef. Savor an exquisite dining experience where delectable cuisine, elegant decor, and stunning views will make for an unforgettable experience. Imaginative culinary creations, top-class wine list, and musical entertainment combine to create the ultimate New York indulgence. While onboard, experience exceptional views of New York City’s iconic skyline from an incredibly unique perspective, live entertainment, and festive décor. Celebrate the holidays on the Hudson and East Rivers with your friends and family. Sample Brunch Menu: STARTER (CHOICE OF ONE) BEET & BABY ARUGULA SALAD (G*)(V) Feta Cheese | Cherry Tomatoes | Balsamic Vinaigrette GREEK YOGURT & GRANOLA PARFAIT (G*)(V) Chobani Non-Fat Greek Yogurt | Honey Granola | Fresh Blueberries and Strawberries MAIN (CHOICE OF ONE) SCRAMBLED EGGS (G*) Nueske's Applewood Triple-Thick Cut Bacon | New Red Potatoes & Cauliflower Hash | Arugula Salad with Champagne Vinaigrette & Red Onions BRIOCHE FRENCH TOAST (V) Stuffed with Nutella Cream | Fresh Strawberries | Maple Syrup (Contains Nuts) OVEN-ROASTED CHICKEN BREAST WITH ROSEMARY & THYME Roasted New Red Potato Salad with Scallions | Haricot Verts | Creamy Mushroom Sauce DESSERT (CHOICE OF ONE) SIGNATURE CHOCOLATE CAKE (V) Creme Anglaise | Raspberry Coulis | Candied Pecans (Contains Nuts) MIXED FRUIT WITH STRAWBERRIES (G*)(VG)(V) Madagascar Vanilla and Orange Cream NEW YORK STYLE CHEESECAKE (V)(N) Lemon Mascarpone Cream | Blueberry Compote May contain Nuts Sample Dinner Menu: STARTER (CHOICE OF ONE - ALL STARTERS ACCOMPANIED BY FRESH BREAD AND BUTTER) BEET & BABY ARUGULA SALAD (G)(V) Feta Cheese | Cherry Tomatoes | Balsamic Vinaigrette SIGNATURE SEAFOOD CHOWDER (G) Clams | Idaho Potatoes | Cream MAIN (CHOICE OF ONE) TURKEY DINNER Garlic Mashed Potato | Traditional Stuffing | Haricot Verts | Turkey Gravy | Cranberry Sauce BROILED SALMON FILET WITH ROASTED TOMATO VINAIGRETTE Lemon Orzo | Farm Fresh Seasonal Vegetables BRAISED BEEF SHORT RIBS WITH FRESNO PEPPER DEMI GLACE (G*) Garlic Mashed Potatoes | Baby Carrots, Broccoli FALL VEGETABLE RAGU (G*)(V)(VG) Butternut Squash | Brussel Sprouts | Cauliflower | Carrots | White Bean Ragu DESSERT (CHOICE OF ONE) HORNBLOWER SIGNATURE CHOCOLATE CAKE (V) Creme Anglaise | Raspberry Coulis | Candied Pecans | (Contains Nuts) MIXED FRUIT WITH STRAWBERRIES (G*)(VG)(V) Madagascar Vanilla and Orange Cream NEW YORK STYLE CHEESECAKE (V) Lemon Marscapone Cream | Blueberry Compote | (Contains Nuts)",
         "Ahoy New York Food Tours has been leading locals and visitors alike on a cultural walk of Chinatown and Little Italy since 2009. On this original food and walking tour of Chinatown and Little Italy, the lively and friendly guides will show you hidden gems and historical sites all while feeding you delicious food. This tour offers a gradual meal with a side dish of history. You will meet your guide in a Chinatown Cafe and from there the food tasting and storytelling begin! Some tastings will be seated while others on the go to ensure that you see and taste as much as possible on this 3-hour food tour. Tastings include (subject to change): A popular Chinese pastry paired with jasmine green tea (seated) A Chinese sponge cake with a twist Authentic Chinese dumplings Scrumptious Roasted Duck Seated and hearty tasting of Italian cuisine with choice of wine or beer Delicious imported Italian cheeses and olives Fresh pasta with an outstanding marinara sauce A well-known Sicilian pastry, cannoli Points of interest include: Chinatown's Mott, Pell and Doyers Streets Transfiguration Church Columbus Park Little Italy's Mulberry and Grand Streets The tour ends in the heart of Little Italy and your guide will make sure to provide you with directions to your next location.",
         "Welcome to our premier scooter rental service located at 117 West 58th Street, just a stone's throw away from the iconic Central Park in New York City. At our store, we offer an exceptional and hassle-free way to explore the beauty of Central Park and its surroundings. Our unique selling points revolve around convenience, quality, and value for your money. We provide fully charged e-scooters, impeccably clean and long-range models, along with complimentary Central Park maps, helmets, and an extra 10-minute grace period for a seamless adventure. Itinerary and Main Activity Features: Upon arriving at our conveniently located store, you'll be warmly greeted by our friendly staff, who will assist you in choosing the perfect e-scooter for your adventure. We offer a variety of rental options, including 1, 2, 3, and 5-hour packages, ensuring that you have the flexibility to explore Central Park and its surroundings at your own pace. Our e-scooters are not just any scooters; they are fully charged and meticulously maintained to guarantee a smooth and enjoyable ride. With extended battery life, you won't have to worry about running out of power mid-tour. Safety is our top priority, and as part of the rental package, we provide helmets to ensure that you're protected throughout your adventure.",
         "Dive into an intimate journey through the heart of NYC's Chinatown with our tour! Explore the vibrant Columbus Park, steeped in historical significance, where the Chinese community gathers. Learn how it transformed from a slum to a cultural haven. Indulge your taste buds at Fried Dumpling, known for its mouthwatering, budget-friendly dumplings, and the historic Nom Wah Tea Parlor, where dim sum delights await. Discover Chinatown's hidden gems, from antique shops to the enchanting Huang Da Xian Taoist Temple, bridging spirituality and culture.Treat yourself to exotic flavors at The Original Chinatown Ice Cream Factory. Their unique ice cream offerings, like lychee and durian, will tantalize your palate. Savor the flavors of Toni's Fresh Rice Noodle, where each bite tells a story of tradition and community. Take a leisurely stroll through the bustling fruit market on Mulberry Street, and discover exotic fruits like dragon fruit and rambutan."]
"""
#extract_keywords(texts)